ALTER SESSION SET CONTAINER = XEPDB1;

-- Create app user and grant privileges
CREATE USER seu IDENTIFIED BY "123";
GRANT CONNECT, RESOURCE TO seu;
GRANT UNLIMITED TABLESPACE TO seu;
GRANT CREATE SESSION TO seu;
GRANT CREATE TABLE TO seu;
GRANT CREATE SEQUENCE TO seu;
GRANT CREATE TRIGGER TO seu;


-- Create app user and grant privileges
CREATE USER sarandy IDENTIFIED BY "123";
GRANT CONNECT, RESOURCE TO sarandy;
GRANT UNLIMITED TABLESPACE TO sarandy;
GRANT CREATE SESSION TO sarandy;
GRANT CREATE TABLE TO sarandy;
GRANT CREATE SEQUENCE TO sarandy;
GRANT CREATE TRIGGER TO sarandy;
