services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "8089:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle123
      APP_USER: seu
      APP_USER_PASSWORD: 123
      ORACLE_DATABASE: system
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle123@//localhost:1521/XEPDB1 AS SYSDBA", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - oracle-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  oracle-data:
    driver: local

networks:
  oracle-network:
    driver: bridge
