services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    # container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "8089:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=EXPRESS
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle123@//localhost:1521/XEPDB1 AS SYSDBA", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - oracle-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  oracle-data:
    driver: local

networks:
  oracle-network:
    driver: bridge
